server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    producer:
      retries: 2
    consumer:
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
